# Generated by Django 5.2.9 on 2025-12-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='DocumentosModel',
        ),
    ]
