# Generated by Django 5.2.9 on 2026-01-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0003_remove_documentosmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
