# Generated by Django 5.2.9 on 2026-01-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0004_documentosmodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosmodel',
            name='ask',
            field=models.TextField(blank=True),
        ),
    ]
